name: test and review python workflow
on: push
jobs:
    job-python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: set up python
        uses: actions/python@v7
        with:
          python-version: '3.13'
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: |
          pytest tests
